### ISSUE TITLE
running Test.R data structure

### ISSUE THREAD

**Issue by eqmh** [eqmh/asymmetric#1]
Hi @jslefche 

I am running the code under the asym_test branch to produce the figures you showed me at SERC.

Are you using the occurrence files to run this code, eg ARGENTINA-PUERTO MADRYN_ipt_occurrence?

thanks!
@eqmh

**Comment by jslefche** [comment]
Yes the ones in the /Data folder!

____________________________
Jonathan S. Lefcheck, Ph.D.
Tennenbaum Coordinating Scientist
MarineGEO: https://marinegeo.si.edu/
Smithsonian Institution
Phone: +1 (443) 482-2443
www.jonlefcheck.net<http://www.jonlefcheck.net>

**Comment by eqmh** [comment]
quick response, dude!

**Comment by eqmh** [comment]
I am getting this error when running lines 28-48:

Error in file(file, "rt") : cannot open the connection
In addition: Warning message:
In file(file, "rt") :
 
 Error in file(file, "rt") : cannot open the connection 

The only changes I made were:
line 23: files <- list.files("C:/Users/Enrique/Documents/asymmetric/data")
line 31: dat <- read.csv(paste0("C:/Users/Enrique/Documents/asymmetric/data", l))

Got a quick fix for this?

Thanks, man.
@eqmh

**Comment by 7yl4r** [comment]
Is that a file i/o error? What's at
"C:/Users/Enrique/Documents/asymmetric/data"?

**Comment by jslefche** [comment]
Looks like are you trying to read in files that aren’t there…see if you can change it to /Data/ and if that works

____________________________
Jonathan S. Lefcheck, Ph.D.
Tennenbaum Coordinating Scientist
MarineGEO: https://marinegeo.si.edu/
Smithsonian Institution
Phone: +1 (443) 482-2443
www.jonlefcheck.net<http://www.jonlefcheck.net>

**Comment by eqmh** [comment]
a bunch of .cvs files

**Comment by eqmh** [comment]
changing it to /Data/ did not work.

I also thought it is a path issue but when I run files <- list.files("C:/Users/Enrique/Documents/asymmetric/data") I get the whole list of files, so I guess the code is pointing at the right directory?

**Comment by eqmh** [comment]
@7yl4r fixed the bug. I was missing a / after data: C:/Users/Enrique/Documents/asymmetric/data/

**Comment by eqmh** [comment]
@jslefche can you please upload the 'sites.csv' file you were using for Test.R?
Thanks

**Comment by jslefche** [comment]
The issue was the summary files being in the `data` directory. I’ve moved those to the root so the script will run

I also added an `output` folder and added the two plots

Carry on!

____________________________
Jonathan S. Lefcheck, Ph.D.
Tennenbaum Coordinating Scientist
MarineGEO: https://marinegeo.si.edu/
Smithsonian Institution
Phone: +1 (443) 482-2443
www.jonlefcheck.net<http://www.jonlefcheck.net>
